import type { Subject } from './types'

export const philosophyES: Subject = {
  id: 'filosofia',
  name: 'Filosofía',
  topics: [
    // Filosofía Antigua
    { id: 'platon', title: 'Platón: teoría de las Ideas y conocimiento.', questions: [
      { id: 'platon-q1', tier: 'standard', prompt: 'Según Platón, ¿qué caracteriza a la realidad sensible?', options: [
        { id: 'a', label: 'La realidad sensible es la realidad definitiva.', isCorrect: false },
        { id: 'b', label: 'Es una copia imperfecta de las Ideas.', isCorrect: true },
        { id: 'c', label: 'Es independiente de las Ideas y accesible por la experiencia.', isCorrect: false },
        { id: 'd', label: 'No puede ser conocida de ningún modo.', isCorrect: false },
      ], explanation: 'Las cosas sensibles son imágenes o copias de las Formas/Ideas, que son el verdadero objeto de conocimiento.' },
      { id: 'platon-q2', tier: 'standard', prompt: '¿Qué son las Ideas para Platón?', options: [
        { id: 'a', label: 'Formas eternas e inmateriales que dan unidad y sentido a las cosas sensibles.', isCorrect: true },
        { id: 'b', label: 'Copia exacta de la realidad sensible.', isCorrect: false },
        { id: 'c', label: 'Simples recuerdos de la memoria.', isCorrect: false },
        { id: 'd', label: 'Ideas que sólo existen para el filósofo.', isCorrect: false },
      ], explanation: 'Las Ideas son realidades eternas e inmateriales que sostienen y dan sentido a las cosas del mundo sensible.' },
      { id: 'platon-q3', tier: 'standard', prompt: '¿Qué método platónico permite a la mente acceder al conocimiento verdadero?', options: [
        { id: 'a', label: 'La dialéctica y la reminiscencia de las Ideas (anamnesis).', isCorrect: true },
        { id: 'b', label: 'La experiencia sensorial directa.', isCorrect: false },
        { id: 'c', label: 'La fe ciega en la autoridad.', isCorrect: false },
        { id: 'd', label: 'La introspección sin orientación.', isCorrect: false },
      ], explanation: 'Con la dialéctica y la reminiscencia de las Ideas, la mente recuerda lo que ya sabía en un estado previo.' },
      { id: 'platon-q4', tier: 'standard', prompt: 'La alegoría de la caverna ilustra...', options: [
        { id: 'a', label: 'La realidad sensible es la única realidad verdadera.', isCorrect: false },
        { id: 'b', label: 'La educación no cambia la percepción de la realidad.', isCorrect: false },
        { id: 'c', label: 'El mundo sensible es una sombra de las Ideas y la filosofía libera la mente.', isCorrect: true },
        { id: 'd', label: 'La filosofía es inútil para alcanzar la verdad.', isCorrect: false },
      ], explanation: 'La caverna muestra que las apariencias sensibles ocultan las Verdades de las Ideas; la filosofía libera al alma.' },
      { id: 'platon-q5', tier: 'standard', prompt: 'En la teoría de las Ideas, ¿cómo se entiende el conocimiento verdadero?', options: [
        { id: 'a', label: 'Es opinión basada en lo sensible.', isCorrect: false },
        { id: 'b', label: 'Es episteme, conocimiento de las Ideas.', isCorrect: true },
        { id: 'c', label: 'Es mera intuición emocional.', isCorrect: false },
        { id: 'd', label: 'Es accesible solo por fe.', isCorrect: false },
      ], explanation: 'El conocimiento verdadero es episteme, conocimiento cierto de las Ideas, no de las apariencias sensibles.' },
      { id: 'platon-q6', tier: 'standard', prompt: '¿Qué afirma Platón sobre la realidad de las Formas (Ideas)?', options: [
        { id: 'a', label: 'Solo las cosas sensibles son reales.', isCorrect: false },
        { id: 'b', label: 'Las Formas son reales y eternas; lo sensible participa de ellas.', isCorrect: true },
        { id: 'c', label: 'Las Formas son solo palabras de la opinión.', isCorrect: false },
        { id: 'd', label: 'No hay diferencia entre sensible y Formas.', isCorrect: false },
      ], explanation: 'Las Formas son realidades eternas e inmutables; el mundo sensible copia y participa de ellas.' },
      { id: 'platon-q7', tier: 'standard', prompt: '¿Qué diferencia hay entre episteme y doxa en Platón?', options: [
        { id: 'a', label: 'Episteme es opinión; doxa es conocimiento.', isCorrect: false },
        { id: 'b', label: 'Episteme es conocimiento verdadero; doxa es opinión.', isCorrect: true },
        { id: 'c', label: 'Ambas son sinónimos.', isCorrect: false },
        { id: 'd', label: 'Doxa es conocimiento divino.', isCorrect: false },
      ], explanation: 'Episteme es saber cierto de las Ideas; doxa es mera apariencia.' },
      { id: 'platon-q8', tier: 'standard', prompt: '¿Qué relación hay entre el alma y las Formas según Platón?', options: [
        { id: 'a', label: 'El alma olvida las Formas y no puede recordarlas.', isCorrect: false },
        { id: 'b', label: 'El alma recuerda las Formas por anamnesis.', isCorrect: true },
        { id: 'c', label: 'El alma no accede a las Formas.', isCorrect: false },
        { id: 'd', label: 'La razón no puede conocer las Formas.', isCorrect: false },
      ], explanation: 'La anámnesis sostiene que el alma reconoce las Formas al filosofar.' },
      { id: 'platon-q9', tier: 'standard', prompt: '¿Qué método platónico es crucial para alcanzar definiciones universales?', options: [
        { id: 'a', label: 'Experiencia empírica.', isCorrect: false },
        { id: 'b', label: 'Dialéctica racional sobre las Ideas.', isCorrect: true },
        { id: 'c', label: 'Autoridad de la tradición.', isCorrect: false },
        { id: 'd', label: 'Retórica persuasiva.', isCorrect: false },
      ], explanation: 'La dialéctica conduce a definiciones universales a partir de las Ideas.' },
      { id: 'platon-q10', tier: 'standard', prompt: 'La idea central del conocimiento para Platón es…', options: [
        { id: 'a', label: 'Fundamentarlo solo en los sentidos.', isCorrect: false },
        { id: 'b', label: 'La reminiscencia de Formas eternas.', isCorrect: true },
        { id: 'c', label: 'Que es incapaz de comprender lo real.', isCorrect: false },
        { id: 'd', label: 'Apoyarse en la tradición.', isCorrect: false },
      ], explanation: 'El conocimiento verdadero consiste en recordar las Formas universales.' },
      { id: 'platon-q11', tier: 'standard', prompt: 'Según Platón, ¿qué son las Ideas (Formas)?', options: [
        { id: 'a', label: 'Son solo apariencias perceptibles por los sentidos.', isCorrect: false },
        { id: 'b', label: 'Son copias imperfectas de las cosas.', isCorrect: false },
        { id: 'c', label: 'Son realidades inmutables y perfectas de las que las cosas sensibles participan.', isCorrect: true },
        { id: 'd', label: 'Son simples opiniones humanas.', isCorrect: false },
      ], explanation: 'Las Formas son realidades inteligibles, perfectas y eternas; las cosas sensibles participan de ellas.' },
      { id: 'platon-q12', tier: 'standard', prompt: '¿Qué representa la Alegoría de la caverna en la epistemología platónica?', options: [
        { id: 'a', label: 'La realidad es solo lo que vemos en la caverna.', isCorrect: false },
        { id: 'b', label: 'La educación libera del mundo sensible hacia el conocimiento de las Formas, especialmente del Bien.', isCorrect: true },
        { id: 'c', label: 'La filosofía es inútil para entender la realidad.', isCorrect: false },
        { id: 'd', label: 'El sol de la caverna representa la verdad subjetiva.', isCorrect: false },
      ], explanation: 'La salida de la caverna simboliza la educación y la iluminación hacia el conocimiento de las Formas.' },
      { id: 'platon-q13', tier: 'standard', prompt: 'La teoría del conocimiento de Platón sostiene que:', options: [
        { id: 'a', label: 'Todo conocimiento es sensible y cambia.', isCorrect: false },
        { id: 'b', label: 'El conocimiento verdadero se alcanza mediante la razón y la contemplación de las Formas.', isCorrect: true },
        { id: 'c', label: 'Todo conocimiento es mera opinión.', isCorrect: false },
        { id: 'd', label: 'La ciencia moderna supera a la filosofía antigua.', isCorrect: false },
      ], explanation: 'El conocimiento verdadero procede de la razón y de la contemplación de las Formas.' },
      { id: 'platon-q14', tier: 'standard', prompt: 'En la teoría de las Ideas, ¿qué relación existe entre las cosas sensibles y las Formas?', options: [
        { id: 'a', label: 'Las cosas sensibles son copias imperfectas de las Formas y participan de ellas.', isCorrect: true },
        { id: 'b', label: 'Las Formas son copias de las cosas sensibles.', isCorrect: false },
        { id: 'c', label: 'No hay relación entre ambos mundos.', isCorrect: false },
        { id: 'd', label: 'Las Formas son meras opiniones humanas.', isCorrect: false },
      ], explanation: 'Las cosas sensibles participan de las Formas y son copias imperfectas de ellas.' },
      { id: 'platon-q15', tier: 'standard', prompt: '¿Qué papel desempeña la Dialéctica en la filosofía de Platón?', options: [
        { id: 'a', label: 'Es un mero juego lógico sin alcance práctico.', isCorrect: false },
        { id: 'b', label: 'Es el método para alcanzar el conocimiento de las Formas mediante el debate y la definición.', isCorrect: true },
        { id: 'c', label: 'Es una técnica retórica para persuadir.', isCorrect: false },
        { id: 'd', label: 'No tiene lugar en su filosofía.', isCorrect: false },
      ], explanation: 'La dialéctica conduce a definiciones y ascenso al mundo inteligible.' },
      { id: 'platon-q16', tier: 'standard', prompt: 'La línea de la epistemología platónica describe la transición de:', options: [
        { id: 'a', label: 'Lo visible (opinión) hacia lo inteligible (conocimiento de las Formas).', isCorrect: true },
        { id: 'b', label: 'La superación de la filosofía por la ciencia.', isCorrect: false },
        { id: 'c', label: 'La experiencia sensible como única fuente de saber.', isCorrect: false },
        { id: 'd', label: 'La verdad como construcción social.', isCorrect: false },
      ], explanation: 'Del mundo visible y opinable al inteligible y cognoscible.' },
      { id: 'platon-add-1', tier: 'standard', prompt: '¿Qué afirma la teoría de las Ideas de Platón?', options: [
        { id: 'a', label: 'Las ideas son solo intuiciones sensibles.', isCorrect: false },
        { id: 'b', label: 'Las ideas son universales y perfectas, existentes independientemente de las cosas sensibles.', isCorrect: true },
        { id: 'c', label: 'La realidad está en las percepciones individuales.', isCorrect: false },
        { id: 'd', label: 'No existe diferencia entre mente y mundo.', isCorrect: false },
      ], explanation: 'Las Formas o Ideas son realidades universales y perfectas; las cosas sensibles son copias.' },
      { id: 'platon-add-2', tier: 'standard', prompt: '¿Qué método de aprendizaje propone la epistemología platónica?', options: [
        { id: 'a', label: 'Observación empírica', isCorrect: false },
        { id: 'b', label: 'Dialéctica y reminiscencia (anámnesis)', isCorrect: true },
        { id: 'c', label: 'Fe ciega', isCorrect: false },
        { id: 'd', label: 'Razonamiento experimental', isCorrect: false },
      ], explanation: 'La dialéctica y la reminiscencia permiten recordar las Ideas universales.' },
      { id: 'platon-add-3', tier: 'standard', prompt: 'En la alegoría de la caverna, las sombras representan...', options: [
        { id: 'a', label: 'La realidad absoluta', isCorrect: false },
        { id: 'b', label: 'Las apariencias sensibles que engañan', isCorrect: true },
        { id: 'c', label: 'Las Ideas perfectas', isCorrect: false },
        { id: 'd', label: 'El conocimiento verdadero', isCorrect: false },
      ], explanation: 'Las sombras simbolizan las apariencias que engañan al mundo sensible.' },
      { id: 'platon-add-4', tier: 'standard', prompt: 'En La República, la justicia se logra cuando...', options: [
        { id: 'a', label: 'El poder está en los especialistas (filósofos-reyes)', isCorrect: true },
        { id: 'b', label: 'Cada persona hace lo que quiere', isCorrect: false },
        { id: 'c', label: 'Todos participan en la asamblea', isCorrect: false },
        { id: 'd', label: 'El poder se hereda', isCorrect: false },
      ], explanation: 'La justicia requiere una élite filosófica que gobierna conforme a la verdad.' },
      { id: 'platon-add-5', tier: 'standard', prompt: 'Según Platón, el conocimiento verdadero es...', options: [
        { id: 'a', label: 'Opinión probable', isCorrect: false },
        { id: 'b', label: 'Creencia en sombras', isCorrect: false },
        { id: 'c', label: 'Conocimiento verdadero de las Ideas', isCorrect: true },
        { id: 'd', label: 'Solo percepción sensible', isCorrect: false },
      ], explanation: 'El conocimiento verdadero es el que alcanza las Ideas, no las sombras.' },
    ] },
    { id: 'aristoteles', title: 'Aristóteles: metafísica, ética y política.', questions: [
      { id: 'aristoteles-q1', tier: 'standard', prompt: 'Para Aristóteles, la sustancia es...', options: [
        { id: 'a', label: 'la combinación de materia y forma.', isCorrect: true },
        { id: 'b', label: 'la materia sin forma.', isCorrect: false },
        { id: 'c', label: 'la forma sin materia.', isCorrect: false },
        { id: 'd', label: 'la experiencia sensible.', isCorrect: false },
      ], explanation: 'La sustancia es la unión de materia y forma; la forma da la esencia y la materia individualiza.' },
      { id: 'aristoteles-q2', tier: 'standard', prompt: '¿Cuáles son las cuatro causas que explica Aristóteles?', options: [
        { id: 'a', label: 'Material, formal, eficiente, final.', isCorrect: true },
        { id: 'b', label: 'Causal, racional, vital, divina.', isCorrect: false },
        { id: 'c', label: 'Materia, forma, potencia, acto.', isCorrect: false },
        { id: 'd', label: 'Ética, política, metafísica, estética.', isCorrect: false },
      ], explanation: 'Las cuatro causas son la material, la formal, la eficiente y la final.' },
      { id: 'aristoteles-q3', tier: 'standard', prompt: 'La Ética a Nicómaco define la eudaimonía como...', options: [
        { id: 'a', label: 'placer.', isCorrect: false },
        { id: 'b', label: 'felicidad y actividad del alma conforme a la virtud.', isCorrect: true },
        { id: 'c', label: 'conocimiento teórico.', isCorrect: false },
        { id: 'd', label: 'poder político.', isCorrect: false },
      ], explanation: 'Eudaimonía es vivir bien, realizando la virtud en acto, no buscar placeres momentáneos.' },
      { id: 'aristoteles-q4', tier: 'standard', prompt: 'En la política de Aristóteles, la ciudad-estado (pólis) busca...', options: [
        { id: 'a', label: 'la realización de intereses personales.', isCorrect: false },
        { id: 'b', label: 'la vida buena mediante la virtud cívica en comunidad.', isCorrect: true },
        { id: 'c', label: 'el dominio de la oligarquía.', isCorrect: false },
        { id: 'd', label: 'la esclavitud universal.', isCorrect: false },
      ], explanation: 'La pólis está orientada a la vida buena mediante la virtud y la organización cívica.' },
      { id: 'aristoteles-q5', tier: 'standard', prompt: 'La virtud moral, para Aristóteles, se alcanza...', options: [
        { id: 'a', label: 'mediante la contemplación teórica.', isCorrect: false },
        { id: 'b', label: 'mediante la moderación y la habituación a través del hábito.', isCorrect: true },
        { id: 'c', label: 'por la sanción divina.', isCorrect: false },
        { id: 'd', label: 'por la obediencia social.', isCorrect: false },
      ], explanation: 'La virtud se cultiva por la habituación y la justeza del término medio.' },
      { id: 'aristoteles-q6', tier: 'standard', prompt: '¿Cuáles son las cuatro causas para explicar una realidad según Aristóteles?', options: [
        { id: 'a', label: 'Material, formal, eficiente y final.', isCorrect: true },
        { id: 'b', label: 'Natural, social, moral y espiritual.', isCorrect: false },
        { id: 'c', label: 'Materia, forma, proporción y finalidad.', isCorrect: false },
        { id: 'd', label: 'Material, espiritual, social y temporal.', isCorrect: false },
      ], explanation: 'Su marco causal clásico: materia, forma, agente y fin.' },
      { id: 'aristoteles-q7', tier: 'standard', prompt: '¿Cómo se adquiere la virtud para Aristóteles?', options: [
        { id: 'a', label: 'Por iluminación divina.', isCorrect: false },
        { id: 'b', label: 'Por hábito y repetición de actos justos.', isCorrect: true },
        { id: 'c', label: 'Solo por contemplación.', isCorrect: false },
        { id: 'd', label: 'Por obediencia a la autoridad.', isCorrect: false },
      ], explanation: 'La virtud moral se forma por hábitos que buscan el término medio.' },
      { id: 'aristoteles-q8', tier: 'standard', prompt: 'Para Aristóteles, la política es…', options: [
        { id: 'a', label: 'La ciencia de la vida buena en común.', isCorrect: true },
        { id: 'b', label: 'La disciplina de la guerra.', isCorrect: false },
        { id: 'c', label: 'Teología de la ciudad.', isCorrect: false },
        { id: 'd', label: 'Economía del Estado.', isCorrect: false },
      ], explanation: 'Estudia el régimen justo y la vida cívica virtuosa.' },
      { id: 'aristoteles-q9', tier: 'standard', prompt: '¿Qué es la sustancia en la metafísica de Aristóteles?', options: [
        { id: 'a', label: 'Es solo la materia sin forma.', isCorrect: false },
        { id: 'b', label: 'La unión de materia y forma; lo que existe por sí mismo.', isCorrect: true },
        { id: 'c', label: 'Un accidente de la realidad.', isCorrect: false },
        { id: 'd', label: 'Una idea universal independiente de las cosas.', isCorrect: false },
      ], explanation: 'La sustancia es sinolo de materia y forma que subsiste por sí.' },
      { id: 'aristoteles-q10', tier: 'standard', prompt: '¿Cuáles son las cuatro causas según Aristóteles?', options: [
        { id: 'a', label: 'Material, Formal, Eficiente y Final.', isCorrect: true },
        { id: 'b', label: 'Material, Espiritual, Eficiente y Temporal.', isCorrect: false },
        { id: 'c', label: 'Mediata, Inmediata, Formal y Final.', isCorrect: false },
        { id: 'd', label: 'Natural, social, moral y psicológica.', isCorrect: false },
      ], explanation: 'Esquema causal clásico aristotélico.' },
      { id: 'aristoteles-q11', tier: 'standard', prompt: 'En la ética de Aristóteles, ¿la virtud se alcanza a través de qué?', options: [
        { id: 'a', label: 'Repetición de normas externas.', isCorrect: false },
        { id: 'b', label: 'Cumplimiento ciego de leyes.', isCorrect: false },
        { id: 'c', label: 'El término medio entre dos extremos viciosos.', isCorrect: true },
        { id: 'd', label: 'Eliminación de la emoción.', isCorrect: false },
      ], explanation: 'La virtud es término medio adquirido por habituación.' },
      { id: 'aristoteles-q12', tier: 'standard', prompt: 'Para Aristóteles, ¿cuál es la finalidad de la pólis?', options: [
        { id: 'a', label: 'La dominación de una élite.', isCorrect: false },
        { id: 'b', label: 'La vida contemplativa aislada.', isCorrect: false },
        { id: 'c', label: 'La vida buena y la realización de la justicia y la felicidad cívica.', isCorrect: true },
        { id: 'd', label: 'La acumulación de riqueza individual.', isCorrect: false },
      ], explanation: 'La pólis busca la vida buena en común.' },
      { id: 'aristoteles-q13', tier: 'standard', prompt: '¿Qué significan acto y potencia en Aristóteles?', options: [
        { id: 'a', label: 'Todo queda en potencia.', isCorrect: false },
        { id: 'b', label: 'La realidad se actualiza cuando una posibilidad se realiza.', isCorrect: true },
        { id: 'c', label: 'La potencia es la realidad misma.', isCorrect: false },
        { id: 'd', label: 'El acto es siempre anterior a la potencia en el tiempo.', isCorrect: false },
      ], explanation: 'Potencia es posibilidad; acto es realización efectiva.' },
      { id: 'aristoteles-q14', tier: 'standard', prompt: 'La teleología en Aristóteles se manifiesta en…', options: [
        { id: 'a', label: 'Simple causalidad eficiente.', isCorrect: false },
        { id: 'b', label: 'Finalidad intrínseca de las cosas naturales y humanas.', isCorrect: true },
        { id: 'c', label: 'Negación de finalidades en la naturaleza.', isCorrect: false },
        { id: 'd', label: 'Búsqueda del placer como fin supremo.', isCorrect: false },
      ], explanation: 'Las cosas tienden a sus fines propios.' },
      { id: 'aristoteles-add-1', tier: 'standard', prompt: 'Para Aristóteles, la sustancia es...', options: [
        { id: 'a', label: 'Solo materia', isCorrect: false },
        { id: 'b', label: 'La unión de materia y forma (hylomorfismo)', isCorrect: true },
        { id: 'c', label: 'Un concepto vacío', isCorrect: false },
        { id: 'd', label: 'Una idea inmutable', isCorrect: false },
      ], explanation: 'La sustancia es la unión de materia y forma (hylomorfismo).' },
      { id: 'aristoteles-add-2', tier: 'standard', prompt: '¿Cuáles son las cuatro causas según Aristóteles?', options: [
        { id: 'a', label: 'Materia, forma, eficiente, final', isCorrect: true },
        { id: 'b', label: 'Materia, forma, ser, conocimiento', isCorrect: false },
        { id: 'c', label: 'Raza, clase, género, destino', isCorrect: false },
        { id: 'd', label: 'Acción, pasión, razón, voluntad', isCorrect: false },
      ], explanation: 'Las cuatro causas son materia, forma, eficiente y final.' },
      { id: 'aristoteles-add-3', tier: 'standard', prompt: 'La virtud ética se define como...', options: [
        { id: 'a', label: 'El extremo (vicio)', isCorrect: false },
        { id: 'b', label: 'La mediación entre exceso y defecto', isCorrect: true },
        { id: 'c', label: 'La felicidad sólo por placer', isCorrect: false },
        { id: 'd', label: 'La obediencia a la ley', isCorrect: false },
      ], explanation: 'La virtud es la mediación entre extremos viciosos.' },
      { id: 'aristoteles-add-4', tier: 'standard', prompt: 'La finalidad de la polis, en Aristóteles, es...', options: [
        { id: 'a', label: 'La autosuficiencia moral', isCorrect: false },
        { id: 'b', label: 'La vida buena (eudaimonía) en sociedad', isCorrect: true },
        { id: 'c', label: 'Expansión territorial', isCorrect: false },
        { id: 'd', label: 'Mantener el orden', isCorrect: false },
      ], explanation: 'La polis existe para desarrollar la vida buena en común.' },
      { id: 'aristoteles-add-5', tier: 'standard', prompt: 'La eudaimonía se alcanza a través de...', options: [
        { id: 'a', label: 'El placer', isCorrect: false },
        { id: 'b', label: 'La virtud y la deliberación razonable en la acción', isCorrect: true },
        { id: 'c', label: 'La riqueza', isCorrect: false },
        { id: 'd', label: 'La gloria', isCorrect: false },
      ], explanation: 'La eudaimonía se consigue mediante la unión de virtud y razonamiento práctico.' },
    ] },

    // Filosofía Medieval
    { id: 'san-agustin', title: 'San Agustín: fe y razón, interioridad.', questions: [
      { id: 'sanagustin-q1', tier: 'standard', prompt: 'Para San Agustín, la fe es necesaria para...', options: [
        { id: 'a', label: 'la razón sin fe.', isCorrect: false },
        { id: 'b', label: 'la fe que precede y guía a la razón para entender la verdad.', isCorrect: true },
        { id: 'c', label: 'la experiencia sensorial.', isCorrect: false },
        { id: 'd', label: 'la razón sin límites.', isCorrect: false },
      ], explanation: 'Agustín sostiene que la fe ilumina la comprensión y guía la razón hacia la verdad.' },
      { id: 'sanagustin-q2', tier: 'standard', prompt: 'La interioridad en Agustín se refiere a...', options: [
        { id: 'a', label: 'la experiencia de Dios dentro del alma.', isCorrect: true },
        { id: 'b', label: 'la experiencia social.', isCorrect: false },
        { id: 'c', label: 'la física del alma.', isCorrect: false },
        { id: 'd', label: 'la obediencia a la autoridad.', isCorrect: false },
      ], explanation: 'La interioridad es el camino hacia Dios en la experiencia del propio interior.' },
      { id: 'sanagustin-q3', tier: 'standard', prompt: 'En la visión agustiniana de la historia, la lucha entre la ciudad de Dios y la ciudad terrenal ilustra...', options: [
        { id: 'a', label: 'la oposición entre fe y razón.', isCorrect: false },
        { id: 'b', label: 'la historia humana orientada por la gracia divina.', isCorrect: true },
        { id: 'c', label: 'la indiferencia ante la verdad.', isCorrect: false },
        { id: 'd', label: 'la primacía de la razón natural sobre la fe.', isCorrect: false },
      ], explanation: 'Agustín describe dos ciudades en conflicto como símbolo de la historia humana orientada por la gracia.' },
      { id: 'sanagustin-q4', tier: 'standard', prompt: 'La interioridad en Agustín se vincula principalmente a...', options: [
        { id: 'a', label: 'la experiencia de Dios en el alma interior.', isCorrect: true },
        { id: 'b', label: 'la contemplación social.', isCorrect: false },
        { id: 'c', label: 'la física del cuerpo.', isCorrect: false },
        { id: 'd', label: 'la autoridad civil.', isCorrect: false },
      ], explanation: 'La experiencia interior de Dios es clave en su epistemología y espiritualidad.' },
      { id: 'sanagustin-q5', tier: 'standard', prompt: '¿Cómo se relacionan fe y razón para San Agustín?', options: [
        { id: 'a', label: 'La fe debe suprimir la razón.', isCorrect: false },
        { id: 'b', label: 'Son compatibles: la fe ilumina la razón.', isCorrect: true },
        { id: 'c', label: 'La razón basta para todo.', isCorrect: false },
        { id: 'd', label: 'La fe contradice la razón.', isCorrect: false },
      ], explanation: 'La fe ordena y guía la razón en la búsqueda de la verdad.' },
      { id: 'sanagustin-q6', tier: 'standard', prompt: '¿Qué propone Agustín con las “dos ciudades”?', options: [
        { id: 'a', label: 'Solo existe la ciudad de Dios.', isCorrect: false },
        { id: 'b', label: 'Coexisten la Ciudad de Dios y la terrenal en tensión.', isCorrect: true },
        { id: 'c', label: 'La ciudad terrenal es la única base de verdad.', isCorrect: false },
        { id: 'd', label: 'La política debe absorber la religión.', isCorrect: false },
      ], explanation: 'Dos órdenes de amor y fines que coexisten en la historia.' },
      { id: 'sanagustin-q7', tier: 'standard', prompt: 'Según Agustín, el tiempo…', options: [
        { id: 'a', label: 'Existe como entidad independiente.', isCorrect: false },
        { id: 'b', label: 'Es distinción mental ligada a memoria y expectación.', isCorrect: true },
        { id: 'c', label: 'Es solo movimiento físico.', isCorrect: false },
        { id: 'd', label: 'No tiene realidad.', isCorrect: false },
      ], explanation: 'El tiempo se mide en el alma: memoria, atención, expectativa.' },
      { id: 'sanagustin-q8', tier: 'standard', prompt: '¿Qué propone San Agustín sobre la relación entre fe y razón?', options: [
        { id: 'a', label: 'Fe y razón son completamente separadas y opuestas.', isCorrect: false },
        { id: 'b', label: 'La fe precede y orienta la razón, iluminándola.', isCorrect: true },
        { id: 'c', label: 'La razón es superior a la fe y la sustituye.', isCorrect: false },
        { id: 'd', label: 'La fe no necesita de la razón en absoluto.', isCorrect: false },
      ], explanation: 'La fe orienta e ilumina a la razón en su búsqueda.' },
      { id: 'sanagustin-q9', tier: 'standard', prompt: 'En la tradición agustiniana, ¿qué significa la interioridad?', options: [
        { id: 'a', label: 'Búsqueda de la verdad fuera del alma.', isCorrect: false },
        { id: 'b', label: 'Introspección que conduce a Dios y a la verdad interior.', isCorrect: true },
        { id: 'c', label: 'Primacía de la experiencia sensorial.', isCorrect: false },
        { id: 'd', label: 'Afirmación de la razón autónoma sin fe.', isCorrect: false },
      ], explanation: 'Interioridad como camino hacia Dios y la verdad.' },
      { id: 'sanagustin-q10', tier: 'standard', prompt: '¿Qué propone la oposición entre la Ciudad de Dios y la Ciudad de los Hombres?', options: [
        { id: 'a', label: 'Dos ciudades físicas distintas.', isCorrect: false },
        { id: 'b', label: 'La terrenal se rige por amor de sí; la de Dios por amor a Dios.', isCorrect: true },
        { id: 'c', label: 'No hay diferencia entre ambas.', isCorrect: false },
        { id: 'd', label: 'Solo existe la de Dios.', isCorrect: false },
      ], explanation: 'Dos órdenes de amor que orientan la historia.' },
      { id: 'sanagustin-add-1', tier: 'standard', prompt: 'Para Agustín, la fe se entiende como...', options: [
        { id: 'a', label: 'Irreconciliable con la razón', isCorrect: false },
        { id: 'b', label: 'Que no necesita razón', isCorrect: false },
        { id: 'c', label: 'Fe que busca la comprensión de la verdad con la ayuda de la razón', isCorrect: true },
        { id: 'd', label: 'Solo fe', isCorrect: false },
      ], explanation: 'La fe ilumina la razón para conocer la verdad.' },
      { id: 'sanagustin-add-2', tier: 'standard', prompt: 'El concepto de iluminación se refiere a...', options: [
        { id: 'a', label: 'Dios ilumina la razón', isCorrect: true },
        { id: 'b', label: 'La luz del sol', isCorrect: false },
        { id: 'c', label: 'La oscuridad de la ignorancia', isCorrect: false },
        { id: 'd', label: 'Nada', isCorrect: false },
      ], explanation: 'La iluminación es la acción de Dios que ilumina la mente.' },
      { id: 'sanagustin-add-3', tier: 'standard', prompt: 'La voluntad libre en Agustín está afectada por el pecado original, pero puede...', options: [
        { id: 'a', label: 'Elegir sólo el mal', isCorrect: false },
        { id: 'b', label: 'Elegir según la gracia', isCorrect: true },
        { id: 'c', label: 'Elegir sin intervención divina', isCorrect: false },
        { id: 'd', label: 'Elegir sin conflicto', isCorrect: false },
      ], explanation: 'La gracia divina asiste la libertad para elegir el bien.' },
      { id: 'sanagustin-add-4', tier: 'standard', prompt: 'La historia humana, según Agustín, es...', options: [
        { id: 'a', label: 'Una lucha entre la ciudad de Dios y la ciudad terrena', isCorrect: true },
        { id: 'b', label: 'Una simple sucesión de eventos', isCorrect: false },
        { id: 'c', label: 'La revelación sin historia', isCorrect: false },
        { id: 'd', label: 'Un destino ya escrito', isCorrect: false },
      ], explanation: 'La historia es la lucha entre dos ciudades: la de Dios y la terrena.' },
    ] },
    { id: 'santo-tomas', title: 'Santo Tomás de Aquino: escolástica, relación entre fe y razón.', questions: [
      { id: 'tomas-q1', tier: 'standard', prompt: 'En Tomás de Aquino, la relación entre fe y razón es...', options: [
        { id: 'a', label: 'fe y razón se oponen.', isCorrect: false },
        { id: 'b', label: 'la fe debe renunciar a la razón.', isCorrect: false },
        { id: 'c', label: 'fe y razón se complementan; la fe ilumina la razón y la razón clarifica la fe.', isCorrect: true },
        { id: 'd', label: 'la razón basta por sí sola para entender todo.', isCorrect: false },
      ], explanation: 'Aquino propone una síntesis: fe y razón se sostienen mutuamente.' },
      { id: 'tomas-q2', tier: 'standard', prompt: '¿Quién es el autor de la obra Summa Theologiae?', options: [
        { id: 'a', label: 'Descartes', isCorrect: false },
        { id: 'b', label: 'Santo Tomás de Aquino', isCorrect: true },
        { id: 'c', label: 'Kant', isCorrect: false },
        { id: 'd', label: 'Aristóteles', isCorrect: false },
      ], explanation: 'Summa Theologiae es la obra cumbre de Aquino.' },
      { id: 'tomas-q3', tier: 'standard', prompt: 'La vía de la analogía del ser de Aquino busca...', options: [
        { id: 'a', label: 'demostrar la existencia de Dios solo por revelación.', isCorrect: false },
        { id: 'b', label: 'explicar la analogía entre ser creador y creado para justificar la existencia de Dios.', isCorrect: true },
        { id: 'c', label: 'separar fe y razón por completo.', isCorrect: false },
        { id: 'd', label: 'dar una prueba empírica de la existencia de Dios.', isCorrect: false },
      ], explanation: 'La analogía del ser permite hablar de Dios sin imágenes antropomórficas.' },
      { id: 'tomas-q4', tier: 'standard', prompt: 'En la relación fe y razón, ¿qué afirma Aquino?', options: [
        { id: 'a', label: 'la fe y la razón son incompatibles.', isCorrect: false },
        { id: 'b', label: 'la razón debe someterse a la fe sin duda.', isCorrect: false },
        { id: 'c', label: 'la fe ilumina la razón y la razón clarifica la fe.', isCorrect: true },
        { id: 'd', label: 'la fe basta para toda verdad.', isCorrect: false },
      ], explanation: 'Aquino sostiene cooperación entre fe y razón; no hay conflicto real entre ambas.' },
      { id: 'tomas-q5', tier: 'standard', prompt: '¿Qué articulan las “cinco vías” de Tomás de Aquino?', options: [
        { id: 'a', label: 'Movimiento, causalidad, contingencia, grados y finalidad.', isCorrect: true },
        { id: 'b', label: 'Solo la fe demuestra a Dios.', isCorrect: false },
        { id: 'c', label: 'La razón supera a la fe en todo.', isCorrect: false },
        { id: 'd', label: 'La moral revela a Dios sin razón.', isCorrect: false },
      ], explanation: 'Vías cosmológicas y teleológicas que fundamentan la existencia de Dios.' },
      { id: 'tomas-q6', tier: 'standard', prompt: '¿Qué es la “analogía del ser” (analogia entis) en Aquino?', options: [
        { id: 'a', label: 'Dios y criaturas comparten ser idéntico.', isCorrect: false },
        { id: 'b', label: 'Se habla de Dios y criatura por analogía, guardando proporción.', isCorrect: true },
        { id: 'c', label: 'La criatura es idéntica a Dios.', isCorrect: false },
        { id: 'd', label: 'No hay analogía posible.', isCorrect: false },
      ], explanation: 'Permite predicar de Dios sin antropomorfismos ni univocidad.' },
      { id: 'tomas-q7', tier: 'standard', prompt: '¿Cómo se coordinan razón natural y revelación en Tomás?', options: [
        { id: 'a', label: 'La razón natural demuestra todo.', isCorrect: false },
        { id: 'b', label: 'La razón alcanza verdades naturales; la revelación, las sobrenaturales.', isCorrect: true },
        { id: 'c', label: 'La revelación sustituye a la razón.', isCorrect: false },
        { id: 'd', label: 'Son inconmensurables.', isCorrect: false },
      ], explanation: 'Síntesis escolástica: dos vías complementarias de verdad.' },
      { id: 'tomas-q8', tier: 'standard', prompt: '¿Qué caracteriza principalmente la Escolástica en Tomás de Aquino?', options: [
        { id: 'a', label: 'Ruptura entre fe y razón.', isCorrect: false },
        { id: 'b', label: 'Dependencia exclusiva de autoridad eclesiástica.', isCorrect: false },
        { id: 'c', label: 'Síntesis entre fe y razón guiada por Aristóteles.', isCorrect: true },
        { id: 'd', label: 'Empirismo por encima de la revelación.', isCorrect: false },
      ], explanation: 'Armoniza fe y razón apoyándose en la filosofía aristotélica.' },
      { id: 'tomas-q9', tier: 'standard', prompt: '¿Qué afirma Tomás de Aquino sobre fe y razón?', options: [
        { id: 'a', label: 'La fe es superior y la razón debe someterse sin cuestionar.', isCorrect: false },
        { id: 'b', label: 'Son independientes y sin diálogo.', isCorrect: false },
        { id: 'c', label: 'Se complementan en la búsqueda de la verdad.', isCorrect: true },
        { id: 'd', label: 'La razón reemplaza a la fe.', isCorrect: false },
      ], explanation: 'Cooperación entre fe y razón.' },
      { id: 'tomas-q10', tier: 'standard', prompt: 'La Quinta Vía de Tomás de Aquino pretende demostrar…', options: [
        { id: 'a', label: 'Una primera causa por el movimiento (vía del motor).', isCorrect: true },
        { id: 'b', label: 'La existencia de Dios por la necesidad del movimiento (general).', isCorrect: false },
        { id: 'c', label: 'La contingencia del universo.', isCorrect: false },
        { id: 'd', label: 'La imposibilidad de demostrar a Dios.', isCorrect: false },
      ], explanation: 'Vía del orden y finalidad (aunque clásicamente la quinta es la teleológica).' },
      { id: 'tomas-q11', tier: 'standard', prompt: 'En Aquino, los universales…', options: [
        { id: 'a', label: 'son meras ideas sin realidad en las cosas.', isCorrect: false },
        { id: 'b', label: 'existen solo como conceptos.', isCorrect: false },
        { id: 'c', label: 'tienen realismo moderado: en Dios y en las cosas.', isCorrect: true },
        { id: 'd', label: 'no deben tratarse en filosofía.', isCorrect: false },
      ], explanation: 'Realismo moderado tomista.' },
      { id: 'tomas-add-1', tier: 'standard', prompt: 'La escolástica pretende...', options: [
        { id: 'a', label: 'Separar fe y razón', isCorrect: false },
        { id: 'b', label: 'Reconciliar fe y razón', isCorrect: true },
        { id: 'c', label: 'Oponerse a la fe', isCorrect: false },
        { id: 'd', label: 'Basarse únicamente en la autoridad', isCorrect: false },
      ], explanation: 'La escolástica busca armonizar fe y razón.' },
      { id: 'tomas-add-2', tier: 'standard', prompt: 'La relación entre fe y razón se manifiesta en que...', options: [
        { id: 'a', label: 'La razón demuestra la existencia de Dios', isCorrect: true },
        { id: 'b', label: 'La fe contradice la razón', isCorrect: false },
        { id: 'c', label: 'La fe no necesita razón', isCorrect: false },
        { id: 'd', label: 'La razón es más alta que la fe', isCorrect: false },
      ], explanation: 'Para Aquino, la razón puede demostrar algunas verdades sobre Dios.' },
      { id: 'tomas-add-3', tier: 'standard', prompt: 'La ley eterna, en la ética tomista, se identifica con...', options: [
        { id: 'a', label: 'La ley natural', isCorrect: false },
        { id: 'b', label: 'La ley divina eterna', isCorrect: true },
        { id: 'c', label: 'La ley humana', isCorrect: false },
        { id: 'd', label: 'La ley de la naturaleza', isCorrect: false },
      ], explanation: 'La ley eterna es la norma divina que rige la realidad.' },
      { id: 'tomas-add-4', tier: 'standard', prompt: 'Con relación a la existencia de Dios, Tomás sostiene que...', options: [
        { id: 'a', label: 'La razón no puede demostrar nada sobre Dios', isCorrect: false },
        { id: 'b', label: 'La fe es suficiente sin razón', isCorrect: false },
        { id: 'c', label: 'La razón puede demostrar a Dios a través de sus pruebas naturales', isCorrect: true },
        { id: 'd', label: 'La existencia de Dios es una opinión', isCorrect: false },
      ], explanation: 'Tomás presenta cinco vías que demuestran la existencia de Dios mediante la razón.' },
    ] },

    // Filosofía Moderna
    { id: 'descartes', title: 'Descartes: racionalismo, duda metódica, cogito.', questions: [
      { id: 'descartes-q1', tier: 'standard', prompt: 'La duda metódica de Descartes tiene como objetivo...', options: [
        { id: 'a', label: 'negar todo conocimiento.', isCorrect: false },
        { id: 'b', label: 'temblar ante toda experiencia sensorial.', isCorrect: false },
        { id: 'c', label: 'llegar a una base de certeza indemostrable para fundamentar el saber.', isCorrect: true },
        { id: 'd', label: 'afirmar la verdad de la fe.', isCorrect: false },
      ], explanation: 'La duda metódica busca una base firme para nuestros conocimientos.' },
      { id: 'descartes-q2', tier: 'standard', prompt: "¿Qué afirma Descartes con 'cogito, ergo sum'?", options: [
        { id: 'a', label: 'El cuerpo es la única realidad.', isCorrect: false },
        { id: 'b', label: 'El pensamiento demuestra la propia existencia.', isCorrect: true },
        { id: 'c', label: 'La experiencia es la única fuente de certeza.', isCorrect: false },
        { id: 'd', label: 'La fe es la base del conocimiento.', isCorrect: false },
      ], explanation: 'El cogito establece la certeza del yo pensante como punto de partida.' },
      { id: 'descartes-q3', tier: 'standard', prompt: 'En la epistemología cartesiana, la razón...', options: [
        { id: 'a', label: 'es la fuente de todo conocimiento válido; la experiencia es susceptible de engaño.', isCorrect: true },
        { id: 'b', label: 'no es fiable y debe abandonarse.', isCorrect: false },
        { id: 'c', label: 'se limita a la opinión común.', isCorrect: false },
        { id: 'd', label: 'solo sirve para demostrar probabilidades.', isCorrect: false },
      ], explanation: 'Descartes defiende la razón como fuente de certeza.' },
      { id: 'descartes-q4', tier: 'standard', prompt: 'Sobre la idea de Dios, ¿qué afirma Descartes?', options: [
        { id: 'a', label: 'La idea de Dios es innata y garantiza la fiabilidad de la razón.', isCorrect: true },
        { id: 'b', label: 'La idea de Dios proviene exclusivamente de la experiencia sensible.', isCorrect: false },
        { id: 'c', label: 'La idea de Dios no es necesaria para la razón.', isCorrect: false },
        { id: 'd', label: 'La idea de Dios es una ficción voluntaria.', isCorrect: false },
      ], explanation: 'La idea innata de un ser perfecto garantiza la veracidad de la razón.' },
      { id: 'descartes-q5', tier: 'standard', prompt: '¿Cuál es la función de la duda metódica en Descartes?', options: [
        { id: 'a', label: 'Conservar escepticismo sin avanzar.', isCorrect: false },
        { id: 'b', label: 'Descartar lo dudoso para hallar certezas indubitables.', isCorrect: true },
        { id: 'c', label: 'Desmontar las verdades de la religión.', isCorrect: false },
        { id: 'd', label: 'Desarrollar empirismo puro.', isCorrect: false },
      ], explanation: 'Método para limpiar el conocimiento y hallar fundamentos firmes.' },
      { id: 'descartes-q6', tier: 'standard', prompt: 'El célebre “cogito” de Descartes afirma…', options: [
        { id: 'a', label: 'Pienso, luego existo.', isCorrect: true },
        { id: 'b', label: 'Los sentidos no engañan nunca.', isCorrect: false },
        { id: 'c', label: 'La mente no puede probar su existencia.', isCorrect: false },
        { id: 'd', label: 'La existencia de Dios es evidente.', isCorrect: false },
      ], explanation: 'El yo pensante se afirma como primera certeza.' },
      { id: 'descartes-q7', tier: 'standard', prompt: '¿Qué papel tiene el “genio maligno” en Descartes?', options: [
        { id: 'a', label: 'Mostrar que todo conocimiento es dudoso para siempre.', isCorrect: false },
        { id: 'b', label: 'Justificar la duda radical ante los sentidos.', isCorrect: true },
        { id: 'c', label: 'Probar sin duda la existencia de Dios.', isCorrect: false },
        { id: 'd', label: 'Fundamentar la intuición sensorial.', isCorrect: false },
      ], explanation: 'Hipótesis que lleva la duda al extremo para buscar certezas.' },
      { id: 'descartes-q8', tier: 'standard', prompt: '¿Qué sostiene Descartes sobre las ideas innatas?', options: [
        { id: 'a', label: 'No existen; todo proviene de la experiencia.', isCorrect: false },
        { id: 'b', label: 'Existen en la mente y no proceden de los sentidos.', isCorrect: true },
        { id: 'c', label: 'Solo las ideas de Dios son innatas.', isCorrect: false },
        { id: 'd', label: 'Son imposibles.', isCorrect: false },
      ], explanation: 'Defiende contenidos innatos como la idea de perfección.' },
      { id: 'descartes-q9', tier: 'standard', prompt: '¿Qué propone la duda metódica de Descartes?', options: [
        { id: 'a', label: 'Dudar de todo para perder la fe.', isCorrect: false },
        { id: 'b', label: 'Dudar de cuanto pueda ponerse en duda para hallar una base indudable.', isCorrect: true },
        { id: 'c', label: 'Dudar solo de ideas claras.', isCorrect: false },
        { id: 'd', label: 'Dudar de la razón y la experiencia por igual.', isCorrect: false },
      ], explanation: 'La duda metódica busca un fundamento cierto del conocimiento.' },
      { id: 'descartes-q10', tier: 'standard', prompt: "¿Qué afirma Descartes con 'cogito, ergo sum'?", options: [
        { id: 'a', label: 'La materia es indudable.', isCorrect: false },
        { id: 'b', label: 'Pensar garantiza la propia existencia.', isCorrect: true },
        { id: 'c', label: 'La existencia de Dios depende de la razón.', isCorrect: false },
        { id: 'd', label: 'La realidad depende de la voluntad.', isCorrect: false },
      ], explanation: 'El acto de pensar prueba la existencia del yo.' },
      { id: 'descartes-q11', tier: 'standard', prompt: '¿Qué postura describe mejor el dualismo mente-cuerpo cartesiano?', options: [
        { id: 'a', label: 'Mente y cuerpo son la misma sustancia.', isCorrect: false },
        { id: 'b', label: 'Mente y cuerpo son sustancias distintas que interactúan.', isCorrect: true },
        { id: 'c', label: 'Solo existe la mente.', isCorrect: false },
        { id: 'd', label: 'Solo existe el cuerpo.', isCorrect: false },
      ], explanation: 'Dualismo entre res cogitans y res extensa.' },
      { id: 'descartes-q12', tier: 'standard', prompt: '¿Qué papel juega Dios en la garantía de certeza según Descartes?', options: [
        { id: 'a', label: 'Es innecesario.', isCorrect: false },
        { id: 'b', label: 'Su perfección garantiza la veracidad de las ideas claras y distintas.', isCorrect: true },
        { id: 'c', label: 'Es ficción de la razón.', isCorrect: false },
        { id: 'd', label: 'Se demuestra por experiencia.', isCorrect: false },
      ], explanation: 'La idea de Dios perfecto asegura la fiabilidad de la razón.' },
      { id: 'descartes-add-1', tier: 'standard', prompt: 'La duda metódica sirve para...', options: [
        { id: 'a', label: 'Fortalecer las creencias previas', isCorrect: false },
        { id: 'b', label: 'Destruir el conocimiento para construir uno seguro', isCorrect: true },
        { id: 'c', label: 'Dudar de todo por siempre', isCorrect: false },
        { id: 'd', label: 'Confirmar la tradición', isCorrect: false },
      ], explanation: 'La duda metódica pretende eliminar dudas para hallar una base segura.' },
      { id: 'descartes-add-2', tier: 'standard', prompt: '“Cogito, ergo sum” se entiende como...', options: [
        { id: 'a', label: 'La prueba de la existencia del mundo externo', isCorrect: false },
        { id: 'b', label: 'La prueba fundante de la existencia del yo que piensa', isCorrect: true },
        { id: 'c', label: 'La duda absoluta', isCorrect: false },
        { id: 'd', label: 'La moral humana', isCorrect: false },
      ], explanation: 'El yo que piensa demuestra su propia existencia indubitable.' },
      { id: 'descartes-add-3', tier: 'standard', prompt: 'Descartes propone el dualismo entre...', options: [
        { id: 'a', label: 'alma y cuerpo como sustancias distintas', isCorrect: true },
        { id: 'b', label: 'razón y emoción', isCorrect: false },
        { id: 'c', label: 'ciencia y fe', isCorrect: false },
        { id: 'd', label: 'mentes y dioses', isCorrect: false },
      ], explanation: 'Mente (res cogitans) y cuerpo (res extensa) son cosas distintas.' },
      { id: 'descartes-add-4', tier: 'standard', prompt: 'El lema de claridad y distinción está asociado a...', options: [
        { id: 'a', label: 'Hume', isCorrect: false },
        { id: 'b', label: 'Descartes', isCorrect: true },
        { id: 'c', label: 'Kant', isCorrect: false },
        { id: 'd', label: 'Spinoza', isCorrect: false },
      ], explanation: 'Descartes propone ideas claras y distintas como criterio de verdad.' },
    ] },
    { id: 'hume', title: 'Hume: empirismo, crítica a la causalidad.', questions: [
      { id: 'hume-q1', tier: 'standard', prompt: 'Para Hume, la causalidad se funda en...', options: [
        { id: 'a', label: 'una conexión necesaria en la naturaleza.', isCorrect: false },
        { id: 'b', label: 'la costumbre o hábito de ver una regularidad en la experiencia.', isCorrect: true },
        { id: 'c', label: 'una demostración a priori.', isCorrect: false },
        { id: 'd', label: 'una intuición innata.', isCorrect: false },
      ], explanation: 'La causalidad es un hábito mental basado en la repetición de experiencias.' },
      { id: 'hume-q2', tier: 'standard', prompt: 'En la teoría del yo de Hume, el yo es...', options: [
        { id: 'a', label: 'una sustancia inmutable.', isCorrect: false },
        { id: 'b', label: 'un conjunto de percepciones en constante cambio.', isCorrect: true },
        { id: 'c', label: 'una idea innata y fija.', isCorrect: false },
        { id: 'd', label: 'una idea derivada de la razón pura.', isCorrect: false },
      ], explanation: 'Para Hume, no hay un yo estable; es una colección de percepciones.' },
      { id: 'hume-q3', tier: 'standard', prompt: 'La crítica de Hume a la causalidad afirma que...', options: [
        { id: 'a', label: 'la causalidad es una verdad innata.', isCorrect: false },
        { id: 'b', label: 'es una construcción de la mente basada en la experiencia.', isCorrect: true },
        { id: 'c', label: 'se establece por la autoridad religiosa.', isCorrect: false },
        { id: 'd', label: 'es demostrable a priori.', isCorrect: false },
      ], explanation: 'No observamos conexiones necesarias, sino regularidades.' },
      { id: 'hume-q4', tier: 'standard', prompt: 'Según Hume, las ideas son...', options: [
        { id: 'a', label: 'impresiones vivas.', isCorrect: false },
        { id: 'b', label: 'copias pálidas de las impresiones.', isCorrect: true },
        { id: 'c', label: 'independientes de las impresiones.', isCorrect: false },
        { id: 'd', label: 'ideas innatas.', isCorrect: false },
      ], explanation: 'Las ideas derivan de impresiones previas.' },
      { id: 'hume-q5', tier: 'standard', prompt: 'Según Hume, la causalidad se basa en…', options: [
        { id: 'a', label: 'Deducción necesaria de la razón.', isCorrect: false },
        { id: 'b', label: 'Hábito y costumbre ante regularidades.', isCorrect: true },
        { id: 'c', label: 'Evidencia empírica irrefutable.', isCorrect: false },
        { id: 'd', label: 'Demostración matemática.', isCorrect: false },
      ], explanation: 'No observamos necesidad causal; inferimos por hábito.' },
      { id: 'hume-q6', tier: 'standard', prompt: '¿Cuál es el límite de la inducción para Hume?', options: [
        { id: 'a', label: 'Está racionalmente garantizada.', isCorrect: false },
        { id: 'b', label: 'No puede justificar que el futuro repita el pasado.', isCorrect: true },
        { id: 'c', label: 'Se prueba por matemáticas.', isCorrect: false },
        { id: 'd', label: 'Es una verdad innata.', isCorrect: false },
      ], explanation: 'La inducción carece de justificación racional estricta.' },
      { id: 'hume-q7', tier: 'standard', prompt: '¿Qué diferencia establece Hume entre impresiones e ideas?', options: [
        { id: 'a', label: 'Las impresiones son copias de las ideas.', isCorrect: false },
        { id: 'b', label: 'Las ideas son copias de las impresiones.', isCorrect: true },
        { id: 'c', label: 'Impresiones e ideas son lo mismo.', isCorrect: false },
        { id: 'd', label: 'Las ideas nacen de la razón; impresiones de la imaginación.', isCorrect: false },
      ], explanation: 'Las ideas derivan de impresiones, que son vivaces.' },
      { id: 'hume-q8', tier: 'standard', prompt: '¿Qué afirma Hume sobre la causalidad?', options: [
        { id: 'a', label: 'Relación necesaria objetiva.', isCorrect: false },
        { id: 'b', label: 'Hábito de la mente por repetición de experiencias.', isCorrect: true },
        { id: 'c', label: 'Ley universal demostrable a priori.', isCorrect: false },
        { id: 'd', label: 'Inexistente en todo caso.', isCorrect: false },
      ], explanation: 'No vemos necesidad, sino regularidad y hábito.' },
      { id: 'hume-q9', tier: 'standard', prompt: 'Sobre los milagros, Hume sostiene que…', options: [
        { id: 'a', label: 'deben aceptarse por fe.', isCorrect: false },
        { id: 'b', label: 'basta con muchos testigos.', isCorrect: false },
        { id: 'c', label: 'son improbables y exigen evidencia extraordinaria.', isCorrect: true },
        { id: 'd', label: 'son imposibles en lógica.', isCorrect: false },
      ], explanation: 'Requiere evidencia superior a la credibilidad del hecho.' },
      { id: 'hume-q10', tier: 'standard', prompt: 'Para Hume, la identidad personal es…', options: [
        { id: 'a', label: 'sustancia invariable.', isCorrect: false },
        { id: 'b', label: 'haz de percepciones en flujo, sin yo estático.', isCorrect: true },
        { id: 'c', label: 'alma eterna.', isCorrect: false },
        { id: 'd', label: 'ficción sin base perceptiva.', isCorrect: false },
      ], explanation: 'No hay sustancia del yo, solo continuidad asociativa.' },
      { id: 'hume-add-1', tier: 'standard', prompt: 'El conocimiento humano, para Hume, se fundamenta principalmente en...', options: [
        { id: 'a', label: 'Ideas innatas', isCorrect: false },
        { id: 'b', label: 'La experiencia sensible', isCorrect: true },
        { id: 'c', label: 'La revelación divina', isCorrect: false },
        { id: 'd', label: 'La razón pura', isCorrect: false },
      ], explanation: 'Todas las ideas proceden de impresiones sensoriales.' },
      { id: 'hume-add-2', tier: 'standard', prompt: 'Hume critica la causalidad alegando que se fundamenta en...', options: [
        { id: 'a', label: 'Necesidad lógica', isCorrect: false },
        { id: 'b', label: 'Costumbre o hábito de la mente', isCorrect: true },
        { id: 'c', label: 'Evidencia empírica robusta', isCorrect: false },
        { id: 'd', label: 'Una revelación divina', isCorrect: false },
      ], explanation: 'La causalidad no se justifica por la razón, sino por la costumbre.' },
      { id: 'hume-add-3', tier: 'standard', prompt: 'Diferencia entre impresiones e ideas según Hume:', options: [
        { id: 'a', label: 'Las ideas son más vívidas que las impresiones', isCorrect: false },
        { id: 'b', label: 'Las impresiones son más vívidas que las ideas', isCorrect: true },
        { id: 'c', label: 'No hay diferencia', isCorrect: false },
        { id: 'd', label: 'Las ideas son solo recuerdos', isCorrect: false },
      ], explanation: 'Impresiones vivaces e ideas derivadas menos vivas.' },
      { id: 'hume-add-4', tier: 'standard', prompt: 'La fundamentación de la ética en Hume se apoya en...', options: [
        { id: 'a', label: 'La razón pura', isCorrect: false },
        { id: 'b', label: 'Los sentimientos y la simpatía', isCorrect: true },
        { id: 'c', label: 'La revelación divina', isCorrect: false },
        { id: 'd', label: 'El utilitarismo', isCorrect: false },
      ], explanation: 'La moral emana de los sentimientos y la simpatía.' },
    ] },
    { id: 'kant', title: 'Kant: criticismo, revolución copernicana, ética del deber.', questions: [
      { id: 'kant-q1', tier: 'standard', prompt: 'La revolución copernicana de Kant sostiene que...', options: [
        { id: 'a', label: 'el objeto determina a la mente.', isCorrect: false },
        { id: 'b', label: 'la mente estructura la experiencia mediante formas y categorías.', isCorrect: true },
        { id: 'c', label: 'la experiencia es ajena a la mente.', isCorrect: false },
        { id: 'd', label: 'solo la fe da certeza.', isCorrect: false },
      ], explanation: 'Las estructuras a priori organizan los datos sensibles.' },
      { id: 'kant-q2', tier: 'standard', prompt: 'Un conocimiento humano requiere...', options: [
        { id: 'a', label: 'estructuras a priori y datos de la experiencia.', isCorrect: true },
        { id: 'b', label: 'solo experiencia sensible.', isCorrect: false },
        { id: 'c', label: 'solo ideas innatas.', isCorrect: false },
        { id: 'd', label: 'fe sin razón.', isCorrect: false },
      ], explanation: 'Síntesis de intuiciones sensibles con conceptos puros.' },
      { id: 'kant-q3', tier: 'standard', prompt: 'El imperativo categórico de Kant afirma que se debe actuar...', options: [
        { id: 'a', label: 'siguiendo deseos personales.', isCorrect: false },
        { id: 'b', label: 'según máximas universalizables.', isCorrect: true },
        { id: 'c', label: 'solo por utilidad.', isCorrect: false },
        { id: 'd', label: 'para obtener placer.', isCorrect: false },
      ], explanation: 'La moral exige universalidad y respeto al deber.' },
      { id: 'kant-q4', tier: 'standard', prompt: 'La distinción fenómeno / cosa en sí indica que...', options: [
        { id: 'a', label: 'podemos conocer la cosa en sí por experiencia.', isCorrect: false },
        { id: 'b', label: 'solo conocemos fenómenos; la cosa en sí es incognoscible.', isCorrect: true },
        { id: 'c', label: 'los fenómenos son ideas innatas.', isCorrect: false },
        { id: 'd', label: 'la cosa en sí es accesible a la razón pura.', isCorrect: false },
      ], explanation: 'Límites del conocimiento humano.' },
      { id: 'kant-q5', tier: 'standard', prompt: 'Un juicio sintético a priori es...', options: [
        { id: 'a', label: 'analítico y a posteriori.', isCorrect: false },
        { id: 'b', label: 'sintético y a priori, amplía conocimiento universal.', isCorrect: true },
        { id: 'c', label: 'analítico y a priori.', isCorrect: false },
        { id: 'd', label: 'empírico y contingente.', isCorrect: false },
      ], explanation: 'Amplía contenido sin depender de la experiencia.' },
      { id: 'kant-q6', tier: 'standard', prompt: '¿Qué expresa la “revolución copernicana” de Kant?', options: [
        { id: 'a', label: 'La mente estructura la experiencia; el objeto se ajusta a sus formas.', isCorrect: true },
        { id: 'b', label: 'La mente se adapta pasivamente a la experiencia.', isCorrect: false },
        { id: 'c', label: 'La razón no tiene límites.', isCorrect: false },
        { id: 'd', label: 'La fe determina la verdad.', isCorrect: false },
      ], explanation: 'El sujeto aporta las formas y categorías que constituyen lo experimentado.' },
      { id: 'kant-q7', tier: 'standard', prompt: '¿Qué son los juicios sintéticos a priori?', options: [
        { id: 'a', label: 'Analíticos sin contenido nuevo.', isCorrect: false },
        { id: 'b', label: 'Aportan contenido y no dependen de la experiencia.', isCorrect: true },
        { id: 'c', label: 'Siempre empíricos.', isCorrect: false },
        { id: 'd', label: 'Injustificables.', isCorrect: false },
      ], explanation: 'Fundamentan ciencias como la matemática y la física.' },
      { id: 'kant-q8', tier: 'standard', prompt: '¿Qué son los postulados de la razón práctica en Kant?', options: [
        { id: 'a', label: 'Creencias prácticas en Dios, libertad e inmortalidad para sostener la moral.', isCorrect: true },
        { id: 'b', label: 'Hechos empíricos sobre la conducta.', isCorrect: false },
        { id: 'c', label: 'Verdades metafísicas demostrables.', isCorrect: false },
        { id: 'd', label: 'Proposiciones sin efecto moral.', isCorrect: false },
      ], explanation: 'Regulativos necesarios de la razón práctica.' },
      { id: 'kant-q9', tier: 'standard', prompt: 'La ética de Kant se organiza alrededor de…', options: [
        { id: 'a', label: 'El utilitarismo.', isCorrect: false },
        { id: 'b', label: 'El deber y el imperativo categórico.', isCorrect: true },
        { id: 'c', label: 'La felicidad personal.', isCorrect: false },
        { id: 'd', label: 'La casualidad de las acciones.', isCorrect: false },
      ], explanation: 'Moral basada en la razón autónoma y universal.' },
      { id: 'kant-q10', tier: 'standard', prompt: '¿Qué indica el “imperativo categórico”?', options: [
        { id: 'a', label: 'Obrar por la propia felicidad.', isCorrect: false },
        { id: 'b', label: 'Obrar solo según máximas universalizables.', isCorrect: true },
        { id: 'c', label: 'Obrar por utilidad.', isCorrect: false },
        { id: 'd', label: 'Obrar por deseo personal.', isCorrect: false },
      ], explanation: 'Criterio formal de universalización de las máximas.' },
      { id: 'kant-q11', tier: 'standard', prompt: '¿Qué significa la “revolución copernicana” de Kant en epistemología?', options: [
        { id: 'a', label: 'El sujeto ajusta lo dado mediante categorías a priori.', isCorrect: true },
        { id: 'b', label: 'Las cosas estructuran al sujeto.', isCorrect: false },
        { id: 'c', label: 'La realidad no puede conocerse en absoluto.', isCorrect: false },
        { id: 'd', label: 'La razón se abandona a la experiencia sin forma.', isCorrect: false },
      ], explanation: 'El objeto se conforma a las condiciones del sujeto.' },
      { id: 'kant-q12', tier: 'standard', prompt: '¿Qué distingue Kant entre fenómenos y noúmenos?', options: [
        { id: 'a', label: 'Fenómenos = incognoscibles; noúmenos = conocidos.', isCorrect: false },
        { id: 'b', label: 'Solo conocemos fenómenos; lo en sí es incognoscible.', isCorrect: true },
        { id: 'c', label: 'Ambos son plenamente cognoscibles.', isCorrect: false },
        { id: 'd', label: 'Los noúmenos sustituyen a los fenómenos.', isCorrect: false },
      ], explanation: 'Límite del conocimiento humano.' },
      { id: 'kant-q13', tier: 'standard', prompt: 'La autonomía de la voluntad en Kant significa…', options: [
        { id: 'a', label: 'Sumisión a autoridad externa.', isCorrect: false },
        { id: 'b', label: 'Ley moral que la razón se da a sí misma.', isCorrect: true },
        { id: 'c', label: 'Búsqueda del placer.', isCorrect: false },
        { id: 'd', label: 'Determinación por el deseo.', isCorrect: false },
      ], explanation: 'Autolegislación racional conforme al deber.' },
      { id: 'kant-q14', tier: 'standard', prompt: 'Sobre juicios a priori/a posteriori y analíticos/sintéticos, Kant sostiene…', options: [
        { id: 'a', label: 'Todos son analíticos a priori.', isCorrect: false },
        { id: 'b', label: 'Existen juicios sintéticos a priori que amplían conocimiento.', isCorrect: true },
        { id: 'c', label: 'Todo es sintético a posteriori.', isCorrect: false },
        { id: 'd', label: 'La experiencia es la única fuente de saber.', isCorrect: false },
      ], explanation: 'Base de la posibilidad de la ciencia.' },
      { id: 'kant-q15', tier: 'standard', prompt: 'La ética de Kant se fundamenta en…', options: [
        { id: 'a', label: 'Utilitarismo y felicidad.', isCorrect: false },
        { id: 'b', label: 'Buena voluntad y deber.', isCorrect: true },
        { id: 'c', label: 'Emociones y empatía.', isCorrect: false },
        { id: 'd', label: 'Consecuencias únicamente.', isCorrect: false },
      ], explanation: 'Deontología basada en la razón práctica.' },
      { id: 'kant-add-1', tier: 'standard', prompt: 'La “revolución copernicana” de Kant consiste en...', options: [
        { id: 'a', label: 'Que la mente estructura la experiencia', isCorrect: true },
        { id: 'b', label: 'Que la experiencia crea la mente', isCorrect: false },
        { id: 'c', label: 'Que el mundo no existe', isCorrect: false },
        { id: 'd', label: 'Que la razón no puede conocer nada', isCorrect: false },
      ], explanation: 'La mente impone estructuras a la experiencia para hacerla posible.' },
      { id: 'kant-add-2', tier: 'standard', prompt: 'Las categorías del entendimiento son...', options: [
        { id: 'a', label: 'ajustes empíricos', isCorrect: false },
        { id: 'b', label: 'formas a priori que estructuran la experiencia', isCorrect: true },
        { id: 'c', label: 'conceptos aprendidos por la cultura', isCorrect: false },
        { id: 'd', label: 'ideas de la razón pura', isCorrect: false },
      ], explanation: 'Categorías como causalidad, sustancia, etc., estructuran la experiencia.' },
      { id: 'kant-add-3', tier: 'standard', prompt: 'Un juicio sintético a priori es...', options: [
        { id: 'a', label: 'Verdad necesaria basada en la lógica (meramente analítica)', isCorrect: false },
        { id: 'b', label: 'Verdad informativa y necesaria a priori', isCorrect: true },
        { id: 'c', label: 'Una proposición empírica', isCorrect: false },
        { id: 'd', label: 'Una afirmación que depende de la experiencia', isCorrect: false },
      ], explanation: 'Añade información sin depender de la experiencia.' },
      { id: 'kant-add-4', tier: 'standard', prompt: 'La ética kantiana se basa en...', options: [
        { id: 'a', label: 'El utilitarismo', isCorrect: false },
        { id: 'b', label: 'El deber (imperativo categórico)', isCorrect: true },
        { id: 'c', label: 'La felicidad como único criterio', isCorrect: false },
        { id: 'd', label: 'La costumbre', isCorrect: false },
      ], explanation: 'El deber y la universalización de máximas.' },
      { id: 'kant-add-5', tier: 'standard', prompt: 'La dignidad humana, para Kant, reside en...', options: [
        { id: 'a', label: 'La utilidad social', isCorrect: false },
        { id: 'b', label: 'La capacidad de autolegislación (autonomía) moral', isCorrect: true },
        { id: 'c', label: 'La riqueza', isCorrect: false },
        { id: 'd', label: 'La fuerza física', isCorrect: false },
      ], explanation: 'La autonomía moral es la base de la dignidad.' },
      { id: 'kant-add-6', tier: 'standard', prompt: 'Para Kant, la experiencia es posible gracias a...', options: [
        { id: 'a', label: 'las formas puras de la intuición: espacio y tiempo', isCorrect: true },
        { id: 'b', label: 'el mundo en sí', isCorrect: false },
        { id: 'c', label: 'la experiencia sensorial no estructurada', isCorrect: false },
        { id: 'd', label: 'la fe', isCorrect: false },
      ], explanation: 'Espacio y tiempo como condiciones a priori.' },
    ] },

    // Filosofía Contemporánea
    { id: 'marx', title: 'Marx: materialismo histórico, alienación.', questions: [
      { id: 'marx-q1', tier: 'standard', prompt: 'El materialismo histórico sostiene que...', options: [
        { id: 'a', label: 'la historia está determinada por ideas.', isCorrect: false },
        { id: 'b', label: 'las fuerzas productivas y relaciones de producción determinan la superestructura.', isCorrect: true },
        { id: 'c', label: 'la economía no influye en la sociedad.', isCorrect: false },
        { id: 'd', label: 'la historia es ciega y sin leyes.', isCorrect: false },
      ], explanation: 'La base económica condiciona la superestructura.' },
      { id: 'marx-q2', tier: 'standard', prompt: 'La alienación, en Marx, se refiere a...', options: [
        { id: 'a', label: 'identificación plena con el trabajo.', isCorrect: false },
        { id: 'b', label: 'separación del trabajador respecto al producto, proceso, especie y comunidad.', isCorrect: true },
        { id: 'c', label: 'condición natural y deseable.', isCorrect: false },
        { id: 'd', label: 'solo se da en la religión.', isCorrect: false },
      ], explanation: 'Describe la desvinculación del trabajador respecto a lo que produce y su esencia.' },
      { id: 'marx-q3', tier: 'standard', prompt: 'La lucha de clases, según Marx, es...', options: [
        { id: 'a', label: 'una idea abstracta sin impacto real.', isCorrect: false },
        { id: 'b', label: 'motor de la historia mediante el conflicto entre clases.', isCorrect: true },
        { id: 'c', label: 'exclusiva de la Edad Moderna.', isCorrect: false },
        { id: 'd', label: 'un obstáculo para la libertad individual.', isCorrect: false },
      ], explanation: 'El conflicto de clases impulsa la transformación histórica.' },
      { id: 'marx-q4', tier: 'standard', prompt: 'La “conciencia de clase” describe...', options: [
        { id: 'a', label: 'la percepción de la clase dominante sobre sí misma.', isCorrect: false },
        { id: 'b', label: 'la percepción distorsionada de la clase trabajadora impuesta por la estructura económica.', isCorrect: true },
        { id: 'c', label: 'la conciencia universal de la libertad.', isCorrect: false },
        { id: 'd', label: 'la ideología religiosa dominante.', isCorrect: false },
      ], explanation: 'Frecuentemente la clase trabajadora percibe su situación desde ópticas ideológicas.' },
      { id: 'marx-q5', tier: 'standard', prompt: '¿Qué futuro vislumbra Marx tras la sociedad comunista?', options: [
        { id: 'a', label: 'Perpetuación de las clases existentes.', isCorrect: false },
        { id: 'b', label: 'Superación de contradicciones y sociedad sin clases según necesidad.', isCorrect: true },
        { id: 'c', label: 'Dictadura permanente del proletariado.', isCorrect: false },
        { id: 'd', label: 'Dominación de ideas burguesas.', isCorrect: false },
      ], explanation: 'Fin de las clases y organización según necesidades.' },
      { id: 'marx-q6', tier: 'standard', prompt: '¿Qué relación establece Marx entre base y superestructura?', options: [
        { id: 'a', label: 'La superestructura determina la base.', isCorrect: false },
        { id: 'b', label: 'La base económica condiciona la superestructura ideológica y política.', isCorrect: true },
        { id: 'c', label: 'Son independientes.', isCorrect: false },
        { id: 'd', label: 'Son idénticas.', isCorrect: false },
      ], explanation: 'La economía condiciona el derecho, la política y la cultura.' },
      { id: 'marx-q7', tier: 'standard', prompt: '¿Qué significa “alienación” en Marx?', options: [
        { id: 'a', label: 'Independencia total del trabajador.', isCorrect: false },
        { id: 'b', label: 'Separación del trabajador de su producto, proceso, especie y comunidad.', isCorrect: true },
        { id: 'c', label: 'Exaltación de la creatividad.', isCorrect: false },
        { id: 'd', label: 'Libertad plena laboral.', isCorrect: false },
      ], explanation: 'Proceso de deshumanización en el trabajo asalariado.' },
      { id: 'marx-q8', tier: 'standard', prompt: '¿Qué concepto describe la “plusvalía”?', options: [
        { id: 'a', label: 'Valor generado por el trabajo que excede el salario del trabajador.', isCorrect: true },
        { id: 'b', label: 'Ganancia de la clase dominante sin relación con el trabajo.', isCorrect: false },
        { id: 'c', label: 'Utilidad de una mercancía.', isCorrect: false },
        { id: 'd', label: 'Inversión en tecnología.', isCorrect: false },
      ], explanation: 'Excedente apropiado por el capitalista sobre el valor del salario.' },
      { id: 'marx-q9', tier: 'standard', prompt: 'La lucha de clases, para Marx, es…', options: [
        { id: 'a', label: 'Un conflicto pasajero sin impacto social.', isCorrect: false },
        { id: 'b', label: 'Dinámica central que impulsa el cambio histórico y social.', isCorrect: true },
        { id: 'c', label: 'Mera cuestión de moral individual.', isCorrect: false },
        { id: 'd', label: 'Fenómeno exclusivamente económico sin influencia cultural.', isCorrect: false },
      ], explanation: 'Motor de transformaciones sociales e históricas.' },
      { id: 'marx-add-1', tier: 'standard', prompt: 'El materialismo histórico sostiene que...', options: [
        { id: 'a', label: 'Las ideas determinan la estructura social', isCorrect: false },
        { id: 'b', label: 'Las relaciones de producción y la base material determinan la superestructura', isCorrect: true },
        { id: 'c', label: 'La historia se rige por caprichos individuales', isCorrect: false },
        { id: 'd', label: 'La economía no influye en la sociedad', isCorrect: false },
      ], explanation: 'La base económica condiciona la superestructura social.' },
      { id: 'marx-add-2', tier: 'standard', prompt: 'La historia está marcada por...', options: [
        { id: 'a', label: 'La lucha de clases', isCorrect: true },
        { id: 'b', label: 'Progreso lineal sin conflicto', isCorrect: false },
        { id: 'c', label: 'Un destino inevitable', isCorrect: false },
        { id: 'd', label: 'La obediencia a la autoridad', isCorrect: false },
      ], explanation: 'El conflicto de clases impulsa el cambio histórico.' },
      { id: 'marx-add-3', tier: 'standard', prompt: 'La alienación, en Marx, se refiere a...', options: [
        { id: 'a', label: 'La separación del trabajador de su producto, de su especie y de su ser', isCorrect: true },
        { id: 'b', label: 'La felicidad del trabajador', isCorrect: false },
        { id: 'c', label: 'La plena autonomía', isCorrect: false },
        { id: 'd', label: 'La realización plena', isCorrect: false },
      ], explanation: 'El trabajador se siente ajeno a su trabajo y a su esencia.' },
      { id: 'marx-add-4', tier: 'standard', prompt: 'La plusvalía es...', options: [
        { id: 'a', label: 'La ganancia obtenida por la explotación del trabajador', isCorrect: true },
        { id: 'b', label: 'La utilidad del capital', isCorrect: false },
        { id: 'c', label: 'La producción de bienes para la sociedad', isCorrect: false },
        { id: 'd', label: 'El valor del trabajo realizado', isCorrect: false },
      ], explanation: 'Diferencia entre valor producido y salario.' },
      { id: 'marx-add-5', tier: 'standard', prompt: 'La crítica a la religión en Marx sugiere...', options: [
        { id: 'a', label: 'La religión es la vía de la verdad', isCorrect: false },
        { id: 'b', label: 'La religión es el opio del pueblo que justifica el status quo', isCorrect: true },
        { id: 'c', label: 'La religión es irrelevante', isCorrect: false },
        { id: 'd', label: 'La religión es la fuente de la ciencia', isCorrect: false },
      ], explanation: 'Consolida la desigualdad y la justifica.' },
    ] },
    { id: 'nietzsche', title: 'Nietzsche: crítica a la moral, voluntad de poder, superhombre.', questions: [
      { id: 'nietzsche-q1', tier: 'standard', prompt: 'La "voluntad de poder" en Nietzsche se entiende como...', options: [
        { id: 'a', label: 'un deseo de dominar a otros a toda costa.', isCorrect: false },
        { id: 'b', label: 'el impulso vital de afirmar, crear y superar límites.', isCorrect: true },
        { id: 'c', label: 'búsqueda exclusiva de poder político.', isCorrect: false },
        { id: 'd', label: 'obediencia a normas sociales.', isCorrect: false },
      ], explanation: 'Impulso fundamental creativo y afirmativo.' },
      { id: 'nietzsche-q2', tier: 'standard', prompt: 'El "superhombre" de Nietzsche representa...', options: [
        { id: 'a', label: 'un tirano político autónomo.', isCorrect: false },
        { id: 'b', label: 'quien crea valores propios y trasciende la moral tradicional.', isCorrect: true },
        { id: 'c', label: 'un ser divino.', isCorrect: false },
        { id: 'd', label: 'una figura del miedo y la sumisión.', isCorrect: false },
      ], explanation: 'Forja valores propios y afirma la vida.' },
      { id: 'nietzsche-q3', tier: 'standard', prompt: 'La “moral de rebaño” a la que se opone Nietzsche es...', options: [
        { id: 'a', label: 'una ética que fomenta la libertad individual.', isCorrect: false },
        { id: 'b', label: 'obediencia ciega a normas tradicionales que limitan la vitalidad.', isCorrect: true },
        { id: 'c', label: 'una ética de la autenticidad.', isCorrect: false },
        { id: 'd', label: 'una moral que valora la creatividad.', isCorrect: false },
      ], explanation: 'Crítica a la moral tradicional que debilita la vitalidad.' },
      { id: 'nietzsche-q4', tier: 'standard', prompt: 'El “eterno retorno” propone...', options: [
        { id: 'a', label: 'repetición infinita de la existencia.', isCorrect: true },
        { id: 'b', label: 'tiempo lineal sin repetición.', isCorrect: false },
        { id: 'c', label: 'vida única que no se repite.', isCorrect: false },
        { id: 'd', label: 'historia sin sentido.', isCorrect: false },
      ], explanation: 'Idea de evaluación vital: vivirías lo mismo si se repitiera eternamente.' },
      { id: 'nietzsche-q5', tier: 'standard', prompt: 'Según Nietzsche, la religión...', options: [
        { id: 'a', label: 'fuente de verdad y guía vital.', isCorrect: false },
        { id: 'b', label: 'construcción que niega la vida y aplasta la existencia individual.', isCorrect: true },
        { id: 'c', label: 'sin influencia moral.', isCorrect: false },
        { id: 'd', label: 'irrelevante para la ética.', isCorrect: false },
      ], explanation: 'Crítica de la religión como negación de la vida.' },
      { id: 'nietzsche-q6', tier: 'standard', prompt: '¿Qué relación hay entre nihilismo y voluntad de poder en Nietzsche?', options: [
        { id: 'a', label: 'El nihilismo debe aceptarse ciegamente.', isCorrect: false },
        { id: 'b', label: 'Puede superarse creando nuevos valores mediante la voluntad de poder.', isCorrect: true },
        { id: 'c', label: 'El nihilismo no existe en su esquema.', isCorrect: false },
        { id: 'd', label: 'La voluntad de poder impide superarlo.', isCorrect: false },
      ], explanation: 'Superación activa del vacío de sentido creando valores propios.' },
      { id: 'nietzsche-q7', tier: 'standard', prompt: '¿Qué critica Nietzsche respecto a la moral tradicional?', options: [
        { id: 'a', label: 'Existencia de valores universales objetivos.', isCorrect: false },
        { id: 'b', label: 'Que impone valores que oprimen la vida y creatividad.', isCorrect: true },
        { id: 'c', label: 'Que fomenta la autenticidad.', isCorrect: false },
        { id: 'd', label: 'Que valora la creatividad por encima de todo.', isCorrect: false },
      ], explanation: 'La moral de rebaño limita la vitalidad.' },
      { id: 'nietzsche-q8', tier: 'standard', prompt: '¿Qué significa “Übermensch” en Nietzsche?', options: [
        { id: 'a', label: 'Ser mágico imposible.', isCorrect: false },
        { id: 'b', label: 'Quien crea valores propios y se supera ante el nihilismo.', isCorrect: true },
        { id: 'c', label: 'Seguidor de normas convencionales.', isCorrect: false },
        { id: 'd', label: 'Figura histórica perfecta.', isCorrect: false },
      ], explanation: 'Figura que crea valores y afirma la vida.' },
      { id: 'nietzsche-q9', tier: 'standard', prompt: 'La crítica al nihilismo pretende…', options: [
        { id: 'a', label: 'Consolidar valores objetivos dados.', isCorrect: false },
        { id: 'b', label: 'Mostrar que la vida carece de sentido.', isCorrect: false },
        { id: 'c', label: 'Provocar la creación de nuevos valores.', isCorrect: true },
        { id: 'd', label: 'Abogar por una moral inmutable.', isCorrect: false },
      ], explanation: 'Invita a crear valores que den sentido.' },
      { id: 'nietzsche-add-1', tier: 'standard', prompt: 'La "crítica de la moral" de Nietzsche sostiene que...', options: [
        { id: 'a', label: 'La moral es universal y eterna', isCorrect: false },
        { id: 'b', label: 'La moral es producto de la genealogía de los valores y está ligada a la voluntad de poder', isCorrect: true },
        { id: 'c', label: 'No existen valores', isCorrect: false },
        { id: 'd', label: 'La moral es la verdad absoluta', isCorrect: false },
      ], explanation: 'La moral es históricamente contingente y ligada a la voluntad de poder.' },
      { id: 'nietzsche-add-2', tier: 'standard', prompt: 'La voluntad de poder describe...', options: [
        { id: 'a', label: 'Una mera inclinación a dominar a otros', isCorrect: false },
        { id: 'b', label: 'La tendencia de afirmar la vida y superar límites', isCorrect: true },
        { id: 'c', label: 'La sumisión ante la autoridad', isCorrect: false },
        { id: 'd', label: 'La pasividad', isCorrect: false },
      ], explanation: 'Fuerza que impulsa a superar límites y afirmar la vida.' },
      { id: 'nietzsche-add-3', tier: 'standard', prompt: 'El concepto de Übermensch (superhombre) representa...', options: [
        { id: 'a', label: 'Un ser débil', isCorrect: false },
        { id: 'b', label: 'Un individuo que crea nuevos valores y va más allá de la moral tradicional', isCorrect: true },
        { id: 'c', label: 'Un dios', isCorrect: false },
        { id: 'd', label: 'Un héroe militar', isCorrect: false },
      ], explanation: 'Trasciende la moral tradicional y crea sus propios valores.' },
      { id: 'nietzsche-add-4', tier: 'standard', prompt: 'La "muerte de Dios" para Nietzsche implica...', options: [
        { id: 'a', label: 'La desaparición de la religión', isCorrect: false },
        { id: 'b', label: 'La crisis de valores y la necesidad de crear nuevos valores', isCorrect: true },
        { id: 'c', label: 'La libertad sin límites', isCorrect: false },
        { id: 'd', label: 'La existencia de un dios nuevo', isCorrect: false },
      ], explanation: 'Abre la responsabilidad de crear nuevos valores.' },
      { id: 'nietzsche-add-5', tier: 'standard', prompt: 'El eterno retorno propone...', options: [
        { id: 'a', label: 'La historia se repite cíclicamente', isCorrect: true },
        { id: 'b', label: 'La historia progresa linealmente', isCorrect: false },
        { id: 'c', label: 'La realidad es estática', isCorrect: false },
        { id: 'd', label: 'La verdad es infinita', isCorrect: false },
      ], explanation: 'Repetición de todos los eventos.' },
    ] },
    { id: 'ortega-gasset', title: 'Ortega y Gasset: perspectivismo, razón vital e histórica.', questions: [
      { id: 'ortega-q1', tier: 'standard', prompt: 'El “perspectivismo” de Ortega sostiene que...', options: [
        { id: 'a', label: 'hay una verdad única accesible a todos.', isCorrect: false },
        { id: 'b', label: 'el conocimiento está situado en la perspectiva y la vida del ser humano.', isCorrect: true },
        { id: 'c', label: 'la verdad es puramente subjetiva.', isCorrect: false },
        { id: 'd', label: 'la razón es guía de la verdad absoluta.', isCorrect: false },
      ], explanation: 'La verdad depende del punto de vista y de las condiciones vitales e históricas.' },
      { id: 'ortega-q2', tier: 'standard', prompt: 'La “razón vital e histórica” señala que...', options: [
        { id: 'a', label: 'la razón es abstracta y ajena a la vida.', isCorrect: false },
        { id: 'b', label: 'la razón está imbricada con la vida y la historia.', isCorrect: true },
        { id: 'c', label: 'la historia es dato empírico sin estructura.', isCorrect: false },
        { id: 'd', label: 'la verdad no depende de la vida.', isCorrect: false },
      ], explanation: 'Entender la razón dentro de la vida y la historia del sujeto.' },
      { id: 'ortega-q3', tier: 'standard', prompt: '“Yo soy yo y mi circunstancia” expresa...', options: [
        { id: 'a', label: 'aislamiento absoluto del individuo.', isCorrect: false },
        { id: 'b', label: 'que el yo se define por su entorno y vida concreta.', isCorrect: true },
        { id: 'c', label: 'primacía de la razón independiente.', isCorrect: false },
        { id: 'd', label: 'negación de la libertad.', isCorrect: false },
      ], explanation: 'Identidad inseparable de la circunstancia histórica y vital.' },
      { id: 'ortega-q4', tier: 'standard', prompt: 'La función de la “razón vital” es...', options: [
        { id: 'a', label: 'separar la vida de la reflexión.', isCorrect: false },
        { id: 'b', label: 'orientar acción y pensamiento desde la vida y sus proyectos.', isCorrect: true },
        { id: 'c', label: 'distinguir ética de estética.', isCorrect: false },
        { id: 'd', label: 'definir verdades universales sin contexto.', isCorrect: false },
      ], explanation: 'Conecta pensamiento y vida para posibilitar proyectos.' },
      { id: 'ortega-q5', tier: 'standard', prompt: 'La verdad, según el perspectivismo, depende de…', options: [
        { id: 'a', label: 'Una visión única universal.', isCorrect: false },
        { id: 'b', label: 'La circunstancia y la perspectiva del sujeto.', isCorrect: true },
        { id: 'c', label: 'Una ciencia ajena a la vida.', isCorrect: false },
        { id: 'd', label: 'La autoridad política.', isCorrect: false },
      ], explanation: 'El conocer está situado histórica y vitalmente.' },
      { id: 'ortega-q6', tier: 'standard', prompt: 'Para Ortega, la vida es…', options: [
        { id: 'a', label: 'Una sucesión de hechos sin proyecto.', isCorrect: false },
        { id: 'b', label: 'Un proyecto situado en la historia y la circunstancia.', isCorrect: true },
        { id: 'c', label: 'Un destino inmutable.', isCorrect: false },
        { id: 'd', label: 'Una cadena causal sin libertad.', isCorrect: false },
      ], explanation: 'Vida como quehacer y proyecto en su circunstancia.' },
      { id: 'ortega-q7', tier: 'standard', prompt: 'Consecuencia educativa del perspectivismo:', options: [
        { id: 'a', label: 'Una única visión universal.', isCorrect: false },
        { id: 'b', label: 'Educar en múltiples perspectivas e historia vital.', isCorrect: true },
        { id: 'c', label: 'Ignorar la biografía del alumno.', isCorrect: false },
        { id: 'd', label: 'Memorizar verdades fijas.', isCorrect: false },
      ], explanation: 'La educación ha de contemplar perspectivas y contextos diversos.' },
      { id: 'ortega-q8', tier: 'standard', prompt: 'La “razón histórica” implica que…', options: [
        { id: 'a', label: 'La razón es independiente de la historia.', isCorrect: false },
        { id: 'b', label: 'La razón se forma dentro de condiciones históricas.', isCorrect: true },
        { id: 'c', label: 'La historia no afecta al razonar.', isCorrect: false },
        { id: 'd', label: 'La razón es atemporal.', isCorrect: false },
      ], explanation: 'El pensar está encarnado en épocas y circunstancias.' },
      { id: 'ortega-q9', tier: 'standard', prompt: '¿Qué papel tiene la libertad en Ortega?', options: [
        { id: 'a', label: 'Ideal abstracto sin relación con la historia.', isCorrect: false },
        { id: 'b', label: 'Condición de la acción humana situada históricamente.', isCorrect: true },
        { id: 'c', label: 'Irrelevante para la filosofía.', isCorrect: false },
        { id: 'd', label: 'Dependiente solo de la autoridad.', isCorrect: false },
      ], explanation: 'Libertad como quehacer en la circunstancia histórica.' },
      { id: 'ortega-q10', tier: 'standard', prompt: '¿Qué propone el perspectivismo de Ortega y Gasset?', options: [
        { id: 'a', label: 'Verdad única y universal sin mediación.', isCorrect: false },
        { id: 'b', label: 'Conocimiento condicionado por situación personal e histórica.', isCorrect: true },
        { id: 'c', label: 'Razón suficiente sin contexto.', isCorrect: false },
        { id: 'd', label: 'La ciencia sustituye la experiencia.', isCorrect: false },
      ], explanation: 'Cada sujeto interpreta desde su circunstancia vital e histórica.' },
      { id: 'ortega-q11', tier: 'standard', prompt: '“Yo soy yo y mi circunstancia” expresa…', options: [
        { id: 'a', label: 'Identidad independiente de la circunstancia.', isCorrect: false },
        { id: 'b', label: 'La vida se realiza en una circunstancia que la condiciona.', isCorrect: true },
        { id: 'c', label: 'La circunstancia no influye en la razón.', isCorrect: false },
        { id: 'd', label: 'Inexistencia de relación ser-circunstancia.', isCorrect: false },
      ], explanation: 'Identidad definida en relación con la circunstancia.' },
      { id: 'ortega-q12', tier: 'standard', prompt: '¿Qué importancia tiene la crítica de Ortega a la “masa”?', options: [
        { id: 'a', label: 'Favorece pensamiento crítico.', isCorrect: false },
        { id: 'b', label: 'Reduce libertad e individualidad en la sociedad moderna.', isCorrect: true },
        { id: 'c', label: 'Eleva el progreso humano siempre.', isCorrect: false },
        { id: 'd', label: 'Es irrelevante para la razón histórica.', isCorrect: false },
      ], explanation: 'La masa puede mermar libertad y amplitud de vida.' },
      { id: 'ortega-add-1', tier: 'standard', prompt: 'Según Ortega, la verdad se entiende desde...', options: [
        { id: 'a', label: 'Una verdad absoluta independiente de la perspectiva', isCorrect: false },
        { id: 'b', label: 'La verdad es relativa a la perspectiva del sujeto y su circunstancia', isCorrect: true },
        { id: 'c', label: 'La verdad no existe', isCorrect: false },
        { id: 'd', label: 'La verdad solo la detentan las ciencias exactas', isCorrect: false },
      ], explanation: 'Perspectivismo: la verdad depende de la perspectiva y la circunstancia.' },
      { id: 'ortega-add-2', tier: 'standard', prompt: 'La “razón vital e histórica” se refiere a...', options: [
        { id: 'a', label: 'Razón abstracta sin vida', isCorrect: false },
        { id: 'b', label: 'Razón que nace de la vida y de la historia del ser humano', isCorrect: true },
        { id: 'c', label: 'Razón de la clase dirigente', isCorrect: false },
        { id: 'd', label: 'Razón divina', isCorrect: false },
      ], explanation: 'La razón debe estar conectada con la vida y la historia.' },
      { id: 'ortega-add-3', tier: 'standard', prompt: 'La expresión “yo y mi circunstancia” señala que...', options: [
        { id: 'a', label: 'El yo presupone una realidad independiente', isCorrect: false },
        { id: 'b', label: 'El yo se define por su circunstancia histórica', isCorrect: true },
        { id: 'c', label: 'La verdad es universal', isCorrect: false },
        { id: 'd', label: 'La circunstancia no importa', isCorrect: false },
      ], explanation: 'El yo se constituye en relación con su entorno histórico y vital.' },
      { id: 'ortega-add-4', tier: 'standard', prompt: 'Para Ortega, la tarea de la filosofía es...', options: [
        { id: 'a', label: 'Buscar verdades universales sin contexto', isCorrect: false },
        { id: 'b', label: 'Confrontar la vida y la historia para entender la realidad', isCorrect: true },
        { id: 'c', label: 'Despreciar la experiencia', isCorrect: false },
        { id: 'd', label: 'Mantener dogmas', isCorrect: false },
      ], explanation: 'Dialogar con la vida y la historia para comprender la realidad.' },
    ] },
    { id: 'hannah-arendt', title: 'Hannah Arendt: totalitarismo, acción política y libertad.', questions: [
      { id: 'arendt-q1', tier: 'standard', prompt: 'En Arendt, el totalitarismo se caracteriza por...', options: [
        { id: 'a', label: 'un régimen de ley y libertad.', isCorrect: false },
        { id: 'b', label: 'dominar todo aspecto de la vida mediante ideología, terror y propaganda.', isCorrect: true },
        { id: 'c', label: 'una democracia que amplía derechos.', isCorrect: false },
        { id: 'd', label: 'un estado que facilita la pluralidad.', isCorrect: false },
      ], explanation: 'Sistema que totaliza el control y suprime la libertad.' },
      { id: 'arendt-q2', tier: 'standard', prompt: 'Para Arendt, la acción política es...', options: [
        { id: 'a', label: 'irrelevante para la libertad.', isCorrect: false },
        { id: 'b', label: 'forma central de libertad en la esfera pública.', isCorrect: true },
        { id: 'c', label: 'solo violencia sin sentido.', isCorrect: false },
        { id: 'd', label: 'un simple trámite burocrático.', isCorrect: false },
      ], explanation: 'La acción política expresa la libertad en la pluralidad.' },
      { id: 'arendt-q3', tier: 'standard', prompt: 'La esfera pública, para Arendt, es...', options: [
        { id: 'a', label: 'un ámbito privado de libertad.', isCorrect: false },
        { id: 'b', label: 'espacio de aparición de la pluralidad y la acción política.', isCorrect: true },
        { id: 'c', label: 'dominio de las leyes sin debate.', isCorrect: false },
        { id: 'd', label: 'lugar de aislamiento individual.', isCorrect: false },
      ], explanation: 'Lugar donde se ejerce la libertad política.' },
      { id: 'arendt-q4', tier: 'standard', prompt: 'Según Arendt, el riesgo último del totalitarismo es...', options: [
        { id: 'a', label: 'fortalecimiento de libertades civiles.', isCorrect: false },
        { id: 'b', label: 'disolución de la verdad y anulación de la libertad por ideología totalizante.', isCorrect: true },
        { id: 'c', label: 'aislamiento de los filósofos.', isCorrect: false },
        { id: 'd', label: 'expansión ilimitada de la democracia.', isCorrect: false },
      ], explanation: 'Sustitución de la verdad por propaganda y supresión de la libertad.' },
      { id: 'arendt-q5', tier: 'standard', prompt: '¿Qué concepto populariza Arendt al estudiar el mal moderno?', options: [
        { id: 'a', label: 'Máquina moral.', isCorrect: false },
        { id: 'b', label: 'Banalidad del mal.', isCorrect: true },
        { id: 'c', label: 'Prudencia ética.', isCorrect: false },
        { id: 'd', label: 'Determinismo histórico.', isCorrect: false },
      ], explanation: 'La normalización de actos atroces por personas corrientes.' },
      { id: 'arendt-q6', tier: 'standard', prompt: 'Para Arendt, la esfera pública es…', options: [
        { id: 'a', label: 'Irrelevante para la política.', isCorrect: false },
        { id: 'b', label: 'Ámbito de aparición, acción y libertad compartida.', isCorrect: true },
        { id: 'c', label: 'Solo administración burocrática.', isCorrect: false },
        { id: 'd', label: 'Sometida totalmente al Estado.', isCorrect: false },
      ], explanation: 'Espacio de deliberación y pluralidad ciudadana.' },
      { id: 'arendt-q7', tier: 'standard', prompt: '¿Qué análisis ofrece Arendt sobre el totalitarismo?', options: [
        { id: 'a', label: 'Simple dictadura clásica basada en la fuerza física.', isCorrect: false },
        { id: 'b', label: 'Fenómeno moderno que deshumaniza mediante propaganda, terror y negación de pluralidad.', isCorrect: true },
        { id: 'c', label: 'Igual a dictaduras anteriores.', isCorrect: false },
        { id: 'd', label: 'Garantiza la libertad colectiva.', isCorrect: false },
      ], explanation: 'Totalización de la vida social mediante ideología y terror.' },
      { id: 'arendt-q8', tier: 'standard', prompt: 'En la teoría de la acción, ¿qué es el “espacio de aparición”?', options: [
        { id: 'a', label: 'Lugar físico aislado.', isCorrect: false },
        { id: 'b', label: 'Espacio social donde los actores aparecen ante otros al actuar.', isCorrect: true },
        { id: 'c', label: 'Habitación privada.', isCorrect: false },
        { id: 'd', label: 'Idea sin importancia práctica.', isCorrect: false },
      ], explanation: 'Ámbito público de visibilidad y acción.' },
      { id: 'arendt-q9', tier: 'standard', prompt: '¿Qué distingue la libertad en Arendt?', options: [
        { id: 'a', label: 'Estado de ánimo privado.', isCorrect: false },
        { id: 'b', label: 'Capacidad de iniciar acciones en el espacio público entre iguales.', isCorrect: true },
        { id: 'c', label: 'Dependencia exclusiva de la riqueza.', isCorrect: false },
        { id: 'd', label: 'Ausencia de política.', isCorrect: false },
      ], explanation: 'Libertad como acción pública.' },
      { id: 'arendt-q10', tier: 'standard', prompt: 'La “banalidad del mal” sugiere que…', options: [
        { id: 'a', label: 'El mal siempre es monstruoso.', isCorrect: false },
        { id: 'b', label: 'Individuos comunes pueden cometer atrocidades por obediencia y falta de reflexión.', isCorrect: true },
        { id: 'c', label: 'El mal es inevitable.', isCorrect: false },
        { id: 'd', label: 'No puede entenderse filosóficamente.', isCorrect: false },
      ], explanation: 'El mal puede surgir de la normalidad burocrática y acrítica.' },
      { id: 'arendt-add-1', tier: 'standard', prompt: 'El totalitarismo, según Arendt, se caracteriza por...', options: [
        { id: 'a', label: 'Un régimen que respeta la pluralidad', isCorrect: false },
        { id: 'b', label: 'Un régimen que niega la pluralidad, la libertad y la raíz del terror mediante propaganda y violencia', isCorrect: true },
        { id: 'c', label: 'Un régimen democrático', isCorrect: false },
        { id: 'd', label: 'La falta de poder', isCorrect: false },
      ], explanation: 'El totalitarismo elimina la pluralidad y recurre al terror.' },
      { id: 'arendt-add-2', tier: 'standard', prompt: 'La libertad, para Arendt, se realiza a través de...', options: [
        { id: 'a', label: 'La pasividad', isCorrect: false },
        { id: 'b', label: 'La acción en el espacio público y la pluralidad', isCorrect: true },
        { id: 'c', label: 'La obediencia', isCorrect: false },
        { id: 'd', label: 'La conciencia individual', isCorrect: false },
      ], explanation: 'La libertad emerge en la acción y la vida pública.' },
      { id: 'arendt-add-3', tier: 'standard', prompt: 'La “banalidad del mal” describe...', options: [
        { id: 'a', label: 'Mal extremo de individuos absolutamente malvados', isCorrect: false },
        { id: 'b', label: 'Mal cometido por personas comunes que actúan sin pensamiento crítico', isCorrect: true },
        { id: 'c', label: 'El mal como fuerza natural', isCorrect: false },
        { id: 'd', label: 'Ninguna', isCorrect: false },
      ], explanation: 'Obediencia ciega y falta de reflexión pueden producir mal.' },
      { id: 'arendt-add-4', tier: 'standard', prompt: 'La libertad efectiva se realiza especialmente a través de...', options: [
        { id: 'a', label: 'La conversación íntima', isCorrect: false },
        { id: 'b', label: 'La acción, el discurso y la participación en el mundo público', isCorrect: true },
        { id: 'c', label: 'El aislamiento', isCorrect: false },
        { id: 'd', label: 'La obediencia', isCorrect: false },
      ], explanation: 'Se manifiesta en la participación pública.' },
    ] },
  ],
}


